/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/Carousel/Carousel.vue')['default']
    CommitteeCard: typeof import('./src/components/Org/CommitteeCard.vue')['default']
    DatesCard: typeof import('./src/components/Home/DatesCard.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FlyerCard: typeof import('./src/components/Home/FlyerCard.vue')['default']
    LocalCard: typeof import('./src/components/LocalAttra/LocalCard.vue')['default']
    LocalPhotos: typeof import('./src/components/LocalAttra/LocalPhotos.vue')['default']
    MemberCard: typeof import('./src/components/Org/MemberCard.vue')['default']
    NavView: typeof import('./src/components/NavView/NavView.vue')['default']
    NewsCard: typeof import('./src/components/Home/NewsCard.vue')['default']
    PaperCard: typeof import('./src/components/Paper/PaperCard.vue')['default']
    ProfileCard: typeof import('./src/components/KeyNotes/ProfileCard.vue')['default']
    ProgramCard: typeof import('./src/components/Program/ProgramCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TBDCard: typeof import('./src/components/TBDView/TBDCard.vue')['default']
    VenueCard: typeof import('./src/components/Venue/VenueCard.vue')['default']
    WelCard: typeof import('./src/components/Home/WelCard.vue')['default']
  }
}
